#!/usr/bin/env zsh

# Another way to profile zsh startup
PROFILE_STARTUP=false
if [[ $PROFILE_STARTUP == true ]]; then
    zmodload zsh/datetime
    PS4='+$EPOCHREALTIME %N:%i> '
    logfile=$(mkdir -p $ZDATADIR/logs && mktemp $ZDATADIR/logs/zsh_profile.XXXXXXXX)
    exec 3>&2 2>>$logfile
    setopt XTRACE
fi

source-safe() { if [ -f "$1" ]; then source "$1"; fi }

#--------------------------------------------------------------#
##          Profile                                           ##
#--------------------------------------------------------------#

if [ "$ZSHRC_PROFILE" != "" ]; then
    zmodload zsh/zprof && zprof > /dev/null
fi

#--------------------------------------------------------------#
##          Base Configuration                                ##
#--------------------------------------------------------------#
source "$ZRCDIR/base.zsh"


#--------------------------------------------------------------#
##          Aliases                                           ##
#--------------------------------------------------------------#
source "$ZRCDIR/alias.zsh"


#--------------------------------------------------------------#
##          Options                                           ##
#--------------------------------------------------------------#
source "$ZRCDIR/options.zsh"


#--------------------------------------------------------------#
##          Completion                                        ##
#--------------------------------------------------------------#
source "$ZRCDIR/completion.zsh"


#--------------------------------------------------------------#
##          Prompt Configuration                              ##
#--------------------------------------------------------------#
if [[ "$TIMESHELL" == "" ]]; then
    if [ ! -d $ZRCDIR/simple ] || command -v virt-what &>/dev/null; then
        source "$ZRCDIR/prompt.zsh"
    else
        autoload -U promptinit && promptinit
        prompt simple
    fi
fi

if ! command -v virt-what &>/dev/null; then
    #--------------------------------------------------------------#
    ##          Function                                          ##
    #--------------------------------------------------------------#
    source "$ZRCDIR/function.zsh"


    #--------------------------------------------------------------#
    ##          Key Bindings                                      ##
    #--------------------------------------------------------------#
    source "$ZRCDIR/bindkey.zsh"


    #--------------------------------------------------------------#
    ##          Plugin                                            ##
    #--------------------------------------------------------------#
    source "$ZRCDIR/plugins.zsh"


    #--------------------------------------------------------------#
    ##          Post Execution                                    ##
    #--------------------------------------------------------------#
    source "$ZRCDIR/post.zsh"
fi

if [[ $PROFILE_STARTUP == true ]]; then
    unsetopt XTRACE
    exec 2>&3 3>&-
fi
