#!/bin/bash
# Put local env or secrets here

# bitwarden-cli with a bit of a hack
export BW_CLIENTID=
export BW_CLIENTSECRET=

BW_MASTER=
BW_HASH=

# Options
AUTO_LOCk=900

exit_error() {
  local code="$1"
  # local message="$2"
  # rofi -e "$message"
  exit "$code"
}

get_session(){
    bw unlock $BW_MASTER 2>/dev/null | grep 'export' | sed -E 's/.*export BW_SESSION="(.*==)"$/\1/' || exit_error $?
}

get_session_key(){
  if [ $AUTO_LOCK -eq 0 ]; then
    keyctl purge user bw_session &>/dev/null
    BW_HASH=$(get_session)
  else
    if ! key_id=$(keyctl request user bw_session 2>/dev/null); then
      session=$(get_session)
      [[ -z "$session" ]] && exit_error 1 "Could not unlock vault"
      key_id=$(echo "$session" | keyctl padd user bw_session @u)
    fi
    
    if [ $AUTO_LOCK -gt 0 ]; then
      keyctl timeout "$key_id" $AUTO_LOCK
    fi
    BW_HASH=$(keyctl pipe "$key_id")
  fi
}

get_session_key

export $BW_HASH
