#!/usr/bin/env bash

CURRENT=$(pwd)

if [[ `command -v git` ]]; then
    git clone --depth=1 --recursive https://github.com/aarnphm/dotfiles.git $CURRENT/dotfiles && cd $CURRENT/dotfiles
    ./install.pre
    ./install.post
else
    echo "git hasn't installed on the system yet. Install git before procedding"
    exit 1
fi

