#!/usr/bin/env bash

set -euo pipefail
trap "exit" INT

DOTS="$HOME/dotfiles"

if [ ! "$(command -v chezmoi)" ]; then
    BIN_DIR="$HOME/.local/bin"
    chezmoi="$BIN_DIR/chezmoi"
    if [ "$(command -v curl)" ]; then
        sh -c "$(curl -fsSL https://git.io/chezmoi)" -- -b "$BIN_DIR"
    elif [ "$(command -v wget)" ]; then
        sh -c "$(wget -qO- https://git.io/chezmoi)" -- -b "$BIN_DIR"
    else
        echo "To install chezmoi, you must have curl or wget installed." >&2
        exit 1
    fi
else
    chezmoi=$(which chezmoi)
fi

if ! builtin command -v git &>/dev/null; then
    gitcmd="$chezmoi --use-builtin-git on"
else
    gitcmd=$(which git)
fi

# includes v2
CHEZMOI_VERSIONS="$($chezmoi --version | cut -d " " -f3)"
is_headless="$(chezmoi data | grep headless | cut -d " " -f4)"

# handles vm or cloud instances
OPTS=(--apply --verbose --debug)
if virt-what &>/dev/null || [[ $is_headless == "true," ]]; then
    OPTS+=(--one-shot)
fi

echo "chezmoi version: $CHEZMOI_VERSIONS"
echo "chezmoi opts: ${OPTS[*]}"

if [[ $CHEZMOI_VERSIONS =~ v2* ]]; then
    \ls -1qA "$("$chezmoi" source-path)" &>/dev/null || exec "$chezmoi" init "${OPTS[*]}" aarnphm
else
    # v1 compatible
    $gitcmd clone --depth=1 --recursive https://github.com/aarnphm/dotfiles.git "$DOTS" && cd "$DOTS"

    # POSIX way to get script's dir: https://stackoverflow.com/a/29834779/12156188
    script_dir="$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)"
    # exec: replace current process with chezmoi init
    exec "$chezmoi" init --apply "--source=$script_dir" -v
fi

if [ "$HOSTNAME" == "archlinux" ]; then
    builtin command -v make &>/dev/null && exec make full-install
elif [[ "$HOSTNAME" == *.local  ]]; then
    exec brew bundle --file=$(chezmoi source-path)/bootstrap/configs/Brewfile
fi
#vim: set ft=sh ts=4 sw=4 tw=0 et :
