#!/bin/sh
# Starts programs only if they aren't already running

# Not mine, props to Boo#3642 (from unixporn disord)
# ---{{{

start() {
    COMMAND=$1
    shift
    ARGS=$*
    pgrep -u "$USER" -ic "$COMMAND" > /dev/null || $COMMAND $ARGS &
}

termstart() {
    COMMAND=$1
    shift
    ARGS=$*
    pgrep -u "$USER" -ic "$COMMAND" > /dev/null || st -n $COMMAND $COMMAND $ARGS &
}

# ---}}}

start xset -b
