let configs = [
      \ "general",
      \ "filetype",
      \ "plugins",
      \ "ui",
      \ "commands",
      \ "mappings",
      \ "settings",
      \]

for file in configs
  let x = expand("~/.config/vim/rcs/".file.".vim")
  if filereadable(x)
    silent! execute 'source ' x
  endif
endfor
"vim: set ft=vim ts=2 sw=2 tw=0 et :
