require("components.battery")
require("components.brightness")
require("components.cpu")
require("components.disk")
require("components.playerctl")
require("components.ram")
require("components.temp")
require("components.volume")
