unsetopt clobber
unsetopt hist_verify
setopt prompt_subst

setopt notify 
setopt correct auto_menu
setopt autocd autopushd multios
setopt complete_in_word
setopt pushd_ignore_dups
setopt pushd_silent pushd_to_home cdable_vars
setopt extendedglob extended_history append_history
setopt hist_reduce_blanks hist_save_no_dups hist_no_store hist_expand
setopt hist_ignore_all_dups inc_append_history
setopt chase_links
setopt nolistambiguous
