
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-08T17:10:34-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "73665b9af9750594e2f051935ba8f3ab5c3c618a",
 "version": "1.0.0b9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
