#!/usr/bin/env sh

set -e

# get datetime
datetime=$(date +'%a %D %T %Z')

cd $(chezmoi source-path)

# Check for new packages, and add it to both .local file
PKGMN=yay
$PKGMN -Qqen >| $HOME/Pacfile.local && $PKGMN -Qqem >| $HOME/Aurfile.local

# Check if upstream, else not pull
if [ $(git rev-parse @)==$(git merge-base @ ${1:-'@{u}'}) ]; then
    git pull --recurse-submodules
fi

# execute scripts
git add -f -v . && git commit -am "$datetime: cron chores" && git push --all

