#!/bin/bash

me="$(readlink -f "$0")"
kebdel=200
kebrate=25
timeout=1200
notify=$((timeout/120))
display=$(systemd-escape -- "$DISPLAY")

configure() {
    xset s $timeout $notify
    xset r rate $kebdel $kebrate
    xset dpms $((timeout * 2)) $((timeout * 22 / 10)) $((timeout * 24 / 10))
}

echo "xss-lock: Running xss-lock daemon..." >&2
configure
export XSECURELOCK_SAVER=saver_blank
playerctl -a pause
exec xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock
#vim: set ft=sh ts=4 sw=4 tw=0 et :
