#!/bin/bash

function test-agent(){
    if [ $(ps ax | grep ssh-agent | wc -l) -gt 0 ] ; then
        echo "ssh-agent is already running"
        ssh-add -l
    else
        eval $(ssh-agent -s)
        if [ "$(ssh-add -l)" == "The agent has no identities." ] ; then
            ssh-add ~/.ssh/id_*
        fi

        # Don't leave extra agents around: kill it on exit. You may not want this part.
        trap "ssh-agent -k" exit
    fi

}


