#!/bin/bash

me="$(readlink -f "$0")"
timeout=600
notify=$((timeout/120))
display=$(systemd-escape -- "$DISPLAY")

configure() {
    xset s $timeout $notify
    xset dpms $((timeout * 2)) $((timeout * 22 / 10)) $((timeout * 24 / 10))
}

echo "xss-lock: Running xss-lock daemon..." >&2
configure
export XSECURELOCK_SAVER=saver_blank
exec xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock
