#!/usr/bin/env zsh

# Another way to profile zsh startup
PROFILE_STARTUP=false
if [[ $PROFILE_STARTUP == true ]]; then
    zmodload zsh/datetime
    PS4='+$EPOCHREALTIME %N:%i> '
    logfile=$(mkdir -p $ZDATADIR/logs && mktemp $ZDATADIR/logs/zsh_profile.XXXXXXXX)
    exec 3>&2 2>>$logfile
    setopt XTRACE
fi

if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
    exec startx
fi

# lazy loading some functions
for function in ${HOME}/.local/bin/*; do
    autoload -Uz ${function:t}
done

source-safe() { if [ -f "$1" ]; then source "$1"; fi }

#--------------------------------------------------------------#
##          Profile                                           ##
#--------------------------------------------------------------#

if [ "$ZSHRC_PROFILE" != "" ]; then
  zmodload zsh/zprof && zprof > /dev/null
fi

#--------------------------------------------------------------#
##          Base Configuration                                ##
#--------------------------------------------------------------#
source "$ZRCDIR/base.zsh"


#--------------------------------------------------------------#
##          Options                                           ##
#--------------------------------------------------------------#
source "$ZRCDIR/option.zsh"


#--------------------------------------------------------------#
##          Completion                                        ##
#--------------------------------------------------------------#
source "$ZRCDIR/completion.zsh"


#--------------------------------------------------------------#
##          Prompt Configuration                              ##
#--------------------------------------------------------------#
if [[ ! -d $ZRCDIR/simple ]]; then
    source "$ZRCDIR/prompt.zsh"
else
    autoload -U promptinit
    promptinit
    prompt simple
fi

#--------------------------------------------------------------#
##          Function                                          ##
#--------------------------------------------------------------#
source "$ZRCDIR/function.zsh"


#--------------------------------------------------------------#
##          Aliases                                           ##
#--------------------------------------------------------------#
source "$ZRCDIR/alias.zsh"


#--------------------------------------------------------------#
##          Key Bindings                                      ##
#--------------------------------------------------------------#
source "$ZRCDIR/bindkey.zsh"


#--------------------------------------------------------------#
##          Plugin                                            ##
#--------------------------------------------------------------#
source "$ZRCDIR/plugins.zsh"


#--------------------------------------------------------------#
##          Post Execution                                    ##
#--------------------------------------------------------------#
source "$ZRCDIR/post.zsh"

source-safe "$ZDOTDIR/.zshrc.local"
source-safe "$ZHOMEDIR/.zshrc.local"

if [[ $PROFILE_STARTUP == true ]]; then
    unsetopt XTRACE
    exec 2>&3 3>&-
fi
